[2024-05-19 01:00:10,566: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 01:00:10,571: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 01:00:10,623: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 01:00:10,623: INFO: common: created directory at: artifacts]
[2024-05-19 01:00:10,623: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 01:00:10,624: ERROR: main: "'ConfigBox' object has no attribute 'local_dir_file'"]
Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_dir_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_dir_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_dir_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_dir_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 503, in box.box.Box.__getitem__
KeyError: 'local_dir_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box/box.py", line 536, in box.box.Box.__getattr__
  File "box/box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'local_dir_file'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box/box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'local_dir_file'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_ingestion_pipeline.py", line 12, in main
    data_ingestion_config = config_manager.get_data_ingestion_config()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/config/configuration.py", line 27, in get_data_ingestion_config
    local_dir_file= config_model.local_dir_file,
  File "box/config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box/box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'local_dir_file'"
[2024-05-19 01:01:00,800: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 01:01:00,802: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 01:01:00,803: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 01:01:00,803: INFO: common: created directory at: artifacts]
[2024-05-19 01:01:00,803: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 01:01:00,803: ERROR: main: 'module' object is not callable]
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_ingestion_pipeline.py", line 14, in main
    data_ingestion = Data_Ingestion(data_ingestion_config = data_ingestion_config)
TypeError: 'module' object is not callable
[2024-05-19 01:02:09,121: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 01:02:09,123: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 01:02:09,123: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 01:02:09,124: INFO: common: created directory at: artifacts]
[2024-05-19 01:02:09,124: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 01:02:09,124: ERROR: main: 'module' object is not callable]
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_ingestion_pipeline.py", line 14, in main
    data_ingestion = Data_Ingestion(data_ingestion_config = data_ingestion_config_model)
TypeError: 'module' object is not callable
[2024-05-19 01:05:48,969: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 01:05:48,971: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 01:05:48,971: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 01:05:48,972: INFO: common: created directory at: artifacts]
[2024-05-19 01:05:48,972: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 01:05:48,972: ERROR: main: module 'Text_Summarization.components.Data_Ingestion' has no attribute 'Data_Ingestion']
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_ingestion_pipeline.py", line 14, in main
    data_ingestion = Data_Ingestion.Data_Ingestion(data_ingestion_config = data_ingestion_config_model)
AttributeError: module 'Text_Summarization.components.Data_Ingestion' has no attribute 'Data_Ingestion'
[2024-05-19 01:08:38,930: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 01:08:38,932: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 01:08:38,933: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 01:08:38,933: INFO: common: created directory at: artifacts]
[2024-05-19 01:08:38,933: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 01:08:40,944: INFO: Data_Ingestion: artifacts/data_ingestion/data.zip download with following info 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 3148:4FFC2:23A2DD:2EEAC9:664903BE
Accept-Ranges: bytes
Date: Sat, 18 May 2024 19:38:40 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100031-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1716061120.729849,VS0,VE719
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9187acff5ffda19b3bdebb432a650a7ec312a0a5
Expires: Sat, 18 May 2024 19:43:40 GMT
Source-Age: 0

]
[2024-05-19 01:08:41,405: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 19:54:07,297: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 19:54:07,304: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:54:07,339: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:54:07,340: INFO: common: created directory at: artifacts]
[2024-05-19 19:54:07,340: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 19:54:07,340: INFO: Data_Ingestion: File already exist]
[2024-05-19 19:54:08,031: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 19:54:08,032: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 19:54:08,039: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:54:08,041: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:54:08,041: INFO: common: created directory at: artifacts]
[2024-05-19 19:54:08,042: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestionsamsum_dataset']
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 22, in <module>
    data_validation.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_validation_pipeline.py", line 15, in main
    data_validator.validate_data()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 29, in validate_data
    raise e
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 14, in validate_data
    all_file_path = os.listdir(os.path.join("artifacts", "data_ingestion" "samsum_dataset"))
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestionsamsum_dataset'
[2024-05-19 19:55:01,922: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 19:55:01,929: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:55:01,931: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:55:01,932: INFO: common: created directory at: artifacts]
[2024-05-19 19:55:01,932: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 19:55:01,933: INFO: Data_Ingestion: File already exist]
[2024-05-19 19:55:02,504: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 19:55:02,504: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 19:55:02,513: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:55:02,515: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:55:02,516: INFO: common: created directory at: artifacts]
[2024-05-19 19:55:02,516: ERROR: main: 'function' object has no attribute 'ALL_FILES_REQUIRED']
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 22, in <module>
    data_validation.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_validation_pipeline.py", line 15, in main
    data_validator.validate_data()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 29, in validate_data
    raise e
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 17, in validate_data
    if file not in self.config_model.ALL_FILES_REQUIRED:
AttributeError: 'function' object has no attribute 'ALL_FILES_REQUIRED'
[2024-05-19 19:57:01,098: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 19:57:01,109: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:57:01,112: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:57:01,112: INFO: common: created directory at: artifacts]
[2024-05-19 19:57:01,113: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 19:57:01,113: INFO: Data_Ingestion: File already exist]
[2024-05-19 19:57:01,729: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 19:57:01,730: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 19:57:01,739: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:57:01,741: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:57:01,741: INFO: common: created directory at: artifacts]
[2024-05-19 19:57:01,742: ERROR: main: 'function' object has no attribute 'ALL_FILES_REQUIRED']
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 22, in <module>
    data_validation.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_validation_pipeline.py", line 15, in main
    data_validator.validate_data()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 29, in validate_data
    raise e
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 17, in validate_data
    if file not in self.config_model.ALL_FILES_REQUIRED:
AttributeError: 'function' object has no attribute 'ALL_FILES_REQUIRED'
[2024-05-19 19:58:47,481: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 19:58:47,487: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:58:47,490: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:58:47,491: INFO: common: created directory at: artifacts]
[2024-05-19 19:58:47,491: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 19:58:47,492: INFO: Data_Ingestion: File already exist]
[2024-05-19 19:58:48,069: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 19:58:48,070: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 19:58:48,079: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:58:48,081: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:58:48,082: INFO: common: created directory at: artifacts]
[2024-05-19 19:58:48,082: ERROR: main: 'function' object has no attribute 'ALL_FILES_REQUIRED']
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 22, in <module>
    data_validation.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_validation_pipeline.py", line 15, in main
    data_validator.validate_data()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 29, in validate_data
    raise e
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 17, in validate_data
    if file not in self.config_model.ALL_FILES_REQUIRED:
AttributeError: 'function' object has no attribute 'ALL_FILES_REQUIRED'
[2024-05-19 19:59:38,252: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 19:59:38,259: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:59:38,261: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:59:38,262: INFO: common: created directory at: artifacts]
[2024-05-19 19:59:38,262: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 19:59:38,263: INFO: Data_Ingestion: File already exist]
[2024-05-19 19:59:38,815: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 19:59:38,815: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 19:59:38,821: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 19:59:38,823: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 19:59:38,823: INFO: common: created directory at: artifacts]
[2024-05-19 19:59:38,823: INFO: Data_Validation: aaaaaaajfjfjfjfjfjfjfjfj <bound method ConfigurationManager.get_data_validation_config of <Text_Summarization.config.configuration.ConfigurationManager object at 0x7f4975fd3bb0>>]
[2024-05-19 19:59:38,824: ERROR: main: 'function' object has no attribute 'ALL_FILES_REQUIRED']
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 22, in <module>
    data_validation.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_validation_pipeline.py", line 15, in main
    data_validator.validate_data()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 31, in validate_data
    raise e
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 19, in validate_data
    if file not in self.config_model.ALL_FILES_REQUIRED:
AttributeError: 'function' object has no attribute 'ALL_FILES_REQUIRED'
[2024-05-19 20:02:37,620: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 20:02:37,628: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:02:37,630: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:02:37,630: INFO: common: created directory at: artifacts]
[2024-05-19 20:02:37,631: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 20:02:37,631: INFO: Data_Ingestion: File already exist]
[2024-05-19 20:02:38,245: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 20:02:38,245: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 20:02:38,251: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:02:38,252: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:02:38,253: INFO: common: created directory at: artifacts]
[2024-05-19 20:02:38,253: INFO: common: created directory at: artifacts/data_validation]
[2024-05-19 20:02:38,254: ERROR: main: name 'logger' is not defined]
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 22, in <module>
    data_validation.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_validation_pipeline.py", line 14, in main
    logger.info(f"aaaaaaajfjfjfjfjfjfjfjfj {dataValidation_model}")
NameError: name 'logger' is not defined
[2024-05-19 20:02:56,717: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 20:02:56,724: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:02:56,726: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:02:56,726: INFO: common: created directory at: artifacts]
[2024-05-19 20:02:56,727: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 20:02:56,727: INFO: Data_Ingestion: File already exist]
[2024-05-19 20:02:57,442: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 20:02:57,442: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 20:02:57,452: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:02:57,455: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:02:57,457: INFO: common: created directory at: artifacts]
[2024-05-19 20:02:57,458: INFO: common: created directory at: artifacts/data_validation]
[2024-05-19 20:02:57,460: INFO: main: >>>>> stage DATA VALIDATION STAGE. completed <<<<<]
[2024-05-19 20:04:06,679: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 20:04:06,686: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:04:06,688: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:04:06,689: INFO: common: created directory at: artifacts]
[2024-05-19 20:04:06,689: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 20:04:06,690: INFO: Data_Ingestion: File already exist]
[2024-05-19 20:04:07,276: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 20:04:07,277: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 20:04:07,285: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:04:07,287: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:04:07,288: INFO: common: created directory at: artifacts]
[2024-05-19 20:04:07,288: INFO: common: created directory at: artifacts/data_validation]
[2024-05-19 20:04:07,292: INFO: main: >>>>> stage DATA VALIDATION STAGE. completed <<<<<]
[2024-05-19 20:05:20,859: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 20:05:20,866: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:05:20,868: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:05:20,869: INFO: common: created directory at: artifacts]
[2024-05-19 20:05:20,869: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 20:05:20,869: INFO: Data_Ingestion: File already exist]
[2024-05-19 20:05:21,442: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 20:05:21,443: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 20:05:21,452: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:05:21,454: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:05:21,455: INFO: common: created directory at: artifacts]
[2024-05-19 20:05:21,455: INFO: common: created directory at: artifacts/data_validation]
[2024-05-19 20:05:21,456: INFO: Data_Validation: 

 vaasadadadad: Validation Status: {validation_status} 

]
[2024-05-19 20:05:21,457: INFO: Data_Validation: 

 vaasadadadad: Validation Status: {validation_status} 

]
[2024-05-19 20:05:21,458: INFO: Data_Validation: 

 vaasadadadad: Validation Status: {validation_status} 

]
[2024-05-19 20:05:21,458: INFO: Data_Validation: 

 vaasadadadad: Validation Status: {validation_status} 

]
[2024-05-19 20:05:21,459: INFO: main: >>>>> stage DATA VALIDATION STAGE. completed <<<<<]
[2024-05-19 20:05:40,922: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 20:05:40,927: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:05:40,929: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:05:40,929: INFO: common: created directory at: artifacts]
[2024-05-19 20:05:40,930: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 20:05:40,930: INFO: Data_Ingestion: File already exist]
[2024-05-19 20:05:41,536: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 20:05:41,537: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 20:05:41,545: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:05:41,547: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:05:41,548: INFO: common: created directory at: artifacts]
[2024-05-19 20:05:41,548: INFO: common: created directory at: artifacts/data_validation]
[2024-05-19 20:05:41,549: ERROR: main: name 'validation_status' is not defined]
Traceback (most recent call last):
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/main.py", line 22, in <module>
    data_validation.main()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/pipeline/Data_validation_pipeline.py", line 18, in main
    data_validator.validate_data()
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 29, in validate_data
    raise e
  File "/home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/src/Text_Summarization/components/Data_Validation.py", line 17, in validate_data
    logger.info(f"\n\n vaasadadadad: Validation Status: {validation_status} \n\n")
NameError: name 'validation_status' is not defined
[2024-05-19 20:06:06,384: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 20:06:06,390: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:06:06,391: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:06:06,392: INFO: common: created directory at: artifacts]
[2024-05-19 20:06:06,392: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 20:06:06,393: INFO: Data_Ingestion: File already exist]
[2024-05-19 20:06:06,936: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 20:06:06,936: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 20:06:06,942: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:06:06,943: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:06:06,944: INFO: common: created directory at: artifacts]
[2024-05-19 20:06:06,945: INFO: common: created directory at: artifacts/data_validation]
[2024-05-19 20:06:06,945: INFO: Data_Validation: 

 vaasadadadad: Validation Status: None 

]
[2024-05-19 20:06:06,946: INFO: Data_Validation: 

 vaasadadadad: Validation Status: None 

]
[2024-05-19 20:06:06,946: INFO: Data_Validation: 

 vaasadadadad: Validation Status: None 

]
[2024-05-19 20:06:06,947: INFO: Data_Validation: 

 vaasadadadad: Validation Status: None 

]
[2024-05-19 20:06:06,947: INFO: main: >>>>> stage DATA VALIDATION STAGE. completed <<<<<]
[2024-05-19 20:47:32,627: INFO: main: >>>>> stage DATA INGESTION STAGE. started <<<<<]
[2024-05-19 20:47:32,630: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:47:32,631: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:47:32,631: INFO: common: created directory at: artifacts]
[2024-05-19 20:47:32,631: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-19 20:47:32,632: INFO: Data_Ingestion: File already exist]
[2024-05-19 20:47:32,941: INFO: main: >>>>> stage DATA INGESTION STAGE. completed <<<<<]
[2024-05-19 20:47:32,941: INFO: main: >>>>> stage DATA VALIDATION STAGE. started <<<<<]
[2024-05-19 20:47:32,944: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/config/config.yaml loaded successfully]
[2024-05-19 20:47:32,944: INFO: common: yaml file: /home/arvin/Desktop/p3r50n47/text_summarization/Text_Summarization/params.yaml loaded successfully]
[2024-05-19 20:47:32,945: INFO: common: created directory at: artifacts]
[2024-05-19 20:47:32,945: INFO: common: created directory at: artifacts/data_validation]
[2024-05-19 20:47:32,945: INFO: Data_Validation: 

 vaasadadadad: Validation Status: None 

]
[2024-05-19 20:47:32,945: INFO: Data_Validation: 

 vaasadadadad: Validation Status: True 

]
[2024-05-19 20:47:32,946: INFO: Data_Validation: 

 vaasadadadad: Validation Status: True 

]
[2024-05-19 20:47:32,946: INFO: Data_Validation: 

 vaasadadadad: Validation Status: False 

]
[2024-05-19 20:47:32,946: INFO: main: >>>>> stage DATA VALIDATION STAGE. completed <<<<<]
